!function(c){function b(g,f){var h=c.proxy(this.process,this),d=c(g).is("body")?c(window):c(g),e;this.options=c.extend({},c.fn.scrollspy.defaults,f);this.$scrollElement=d.on("scroll.scroll-spy.data-api",h);this.selector=(this.options.target||((e=c(g).attr("href"))&&e.replace(/.*(?=#[^\s]+$)/,""))||"")+" .nav li > a";this.$body=c("body");this.refresh();this.process()}
b.prototype={constructor:b,refresh:function(){var d=this,e;this.offsets=c([]);this.targets=c([]);e=this.$body.find(this.selector).map(function(){var g=c(this),f=g.data("target")||g.attr("href"),h=/^#\w/.test(f)&&c(f);return(h&&h.length&&[[h.position().top+(!c.isWindow(d.$scrollElement.get(0))&&d.$scrollElement.scrollTop()),f]])||null}).sort(function(g,f){return g[0]-f[0]}).each(function(){d.offsets.push(this[0]);d.targets.push(this[1])})},process:function(){var j=this.$scrollElement.scrollTop()+this.options.offset,f=this.$scrollElement[0].scrollHeight||this.$body[0].scrollHeight,h=f-this.$scrollElement.height(),g=this.offsets,d=this.targets,k=this.activeTarget,e;if(j>=h){return k!=(e=d.last()[0])&&this.activate(e)}
for(e=g.length;e--;){k!=d[e]&&j>=g[e]&&(!g[e+1]||j<=g[e+1])&&this.activate(d[e])}},activate:function(f){var e,d;this.activeTarget=f;c(this.selector).parent(".active").removeClass("active");d=this.selector+'[data-target="'+f+'"],'+this.selector+'[href="'+f+'"]';e=c(d).parent("li").addClass("active");if(e.parent(".dropdown-menu").length){e=e.closest("li.dropdown").addClass("active")}
e.trigger("activate")}};var a=c.fn.scrollspy;c.fn.scrollspy=function(d){return this.each(function(){var g=c(this),f=g.data("scrollspy"),e=typeof d=="object"&&d;if(!f){g.data("scrollspy",(f=new b(this,e)))}
if(typeof d=="string"){f[d]()}})};c.fn.scrollspy.Constructor=b;c.fn.scrollspy.defaults={offset:100};c.fn.scrollspy.noConflict=function(){c.fn.scrollspy=a;return this};c(window).on("load",function(){c('[data-spy="scroll"]').each(function(){var d=c(this);d.scrollspy(d.data())})})}(window.jQuery);!function(f){var b="[data-toggle=dropdown]",a=function(h){var g=f(h).on("click.dropdown.data-api",this.toggle);f("html").on("click.dropdown.data-api",function(){g.parent().removeClass("open")})};a.prototype={constructor:a,toggle:function(j){var i=f(this),h,g;if(i.is(".disabled, :disabled")){return}
h=e(i);g=h.hasClass("open");d();if(!g){h.toggleClass("open")}
i.focus();return false},keydown:function(l){var k,m,g,j,i,h;if(!/(38|40|27)/.test(l.keyCode)){return}
k=f(this);l.preventDefault();l.stopPropagation();if(k.is(".disabled, :disabled")){return}
j=e(k);i=j.hasClass("open");if(!i||(i&&l.keyCode==27)){if(l.which==27){j.find(b).focus()}
return k.click()}
m=f("[role=menu] li:not(.divider):visible a",j);if(!m.length){return}
h=m.index(m.filter(":focus"));if(l.keyCode==38&&h>0){h--}
if(l.keyCode==40&&h<m.length-1){h++}
if(!~h){h=0}
m.eq(h).focus()}};function d(){f(b).each(function(){e(f(this)).removeClass("open")})}
function e(i){var g=i.attr("data-target"),h;if(!g){g=i.attr("href");g=g&&/#/.test(g)&&g.replace(/.*(?=#[^\s]*$)/,"")}
h=g&&f(g);if(!h||!h.length){h=i.parent()}
return h}
var c=f.fn.dropdown;f.fn.dropdown=function(g){return this.each(function(){var i=f(this),h=i.data("dropdown");if(!h){i.data("dropdown",(h=new a(this)))}
if(typeof g=="string"){h[g].call(i)}})};f.fn.dropdown.Constructor=a;f.fn.dropdown.noConflict=function(){f.fn.dropdown=c;return this};f(document).on("click.dropdown.data-api",d).on("click.dropdown.data-api",".dropdown form",function(g){g.stopPropagation()}).on(".dropdown-menu",function(g){g.stopPropagation()}).on("click.dropdown.data-api",b,a.prototype.toggle).on("keydown.dropdown.data-api",b+", [role=menu]",a.prototype.keydown)}(window.jQuery);!function(a){a(function(){a.support.transition=(function(){var b=(function(){var e=document.createElement("bootstrap"),d={WebkitTransition:"webkitTransitionEnd",MozTransition:"transitionend",OTransition:"oTransitionEnd otransitionend",transition:"transitionend"},c;for(c in d){if(e.style[c]!==undefined){return d[c]}}}());return b&&{end:b}})()})}(window.jQuery);!function(b){var c=function(e,d){this.$element=b(e);this.options=b.extend({},b.fn.collapse.defaults,d);if(this.options.parent){this.$parent=b(this.options.parent)}
this.options.toggle&&this.toggle()};c.prototype={constructor:c,dimension:function(){var d=this.$element.hasClass("width");return d?"width":"height"},show:function(){var g,d,f,e;if(this.transitioning||this.$element.hasClass("in")){return}
g=this.dimension();d=b.camelCase(["scroll",g].join("-"));f=this.$parent&&this.$parent.find("> .accordion-group > .in");if(f&&f.length){e=f.data("collapse");if(e&&e.transitioning){return}
f.collapse("hide");e||f.data("collapse",null)}
this.$element[g]("auto");this.transition("addClass",b.Event("show"),"shown");b.support.transition&&this.$element[g](this.$element[0][d]);this.$element.css({overflow:"visible"})},hide:function(){var d;if(this.transitioning||!this.$element.hasClass("in")){return}
d=this.dimension();this.reset(this.$element[d]());this.transition("removeClass",b.Event("hide"),"hidden");this.$element[d](0);this.$element.css({overflow:"hidden"})},reset:function(d){var e=this.dimension();this.$element.removeClass("collapse")[e](d||"auto")[0].offsetWidth;this.$element[d!==null?"addClass":"removeClass"]("collapse");return this},transition:function(h,e,f){var g=this,d=function(){if(e.type=="show"){g.reset()}
g.transitioning=0;g.$element.trigger(f)};this.$element.trigger(e);if(e.isDefaultPrevented()){return}
this.transitioning=1;this.$element[h]("in");b.support.transition&&this.$element.hasClass("collapse")?this.$element.one(b.support.transition.end,d):d()},toggle:function(){this[this.$element.hasClass("in")?"hide":"show"]()}};var a=b.fn.collapse;b.fn.collapse=function(d){return this.each(function(){var g=b(this),f=g.data("collapse"),e=b.extend({},b.fn.collapse.defaults,g.data(),typeof d=="object"&&d);if(!f){g.data("collapse",(f=new c(this,e)))}
if(typeof d=="string"){f[d]()}})};b.fn.collapse.defaults={toggle:true};b.fn.collapse.Constructor=c;b.fn.collapse.noConflict=function(){b.fn.collapse=a;return this};b(document).on("click.collapse.data-api","[data-toggle=collapse]",function(i){var h=b(this),d,g=h.attr("data-target")||i.preventDefault()||(d=h.attr("href"))&&d.replace(/.*(?=#[^\s]+$)/,""),f=b(g).data("collapse")?"toggle":h.data();h[b(g).hasClass("in")?"addClass":"removeClass"]("collapsed");b(g).collapse(f)})}(window.jQuery);(function($){$(document).ready(function(){$('.cloud-zoom, .cloud-zoom-gallery').CloudZoom()});function format(str){for(var i=1;i<arguments.length;i++){str=str.replace('%'+(i-1),arguments[i])}
return str}
function CloudZoom(jWin,opts){var sImg=$('img',jWin);var img1;var img2;var zoomDiv=null;var $mouseTrap=null;var lens=null;var $tint=null;var softFocus=null;var $ie6Fix=null;var zoomImage;var controlTimer=0;var cw,ch;var destU=0;var destV=0;var currV=0;var currU=0;var filesLoaded=0;var mx,my;var ctx=this,zw;setTimeout(function(){if($mouseTrap===null){var w=jWin.width();jWin.parent().append(format('<div style="width:%0px;position:absolute;top:75%;left:%1px;text-align:center" class="cloud-zoom-loading" >Loading...</div>',w/3,(w/2)-(w/6))).find(':last').css('opacity',0.5)}},200);var ie6FixRemove=function(){if($ie6Fix!==null){$ie6Fix.remove();$ie6Fix=null}};this.removeBits=function(){if(lens){lens.remove();lens=null}
if($tint){$tint.remove();$tint=null}
if(softFocus){softFocus.remove();softFocus=null}
ie6FixRemove();$('.cloud-zoom-loading',jWin.parent()).remove()};this.destroy=function(){jWin.data('zoom',null);if($mouseTrap){$mouseTrap.unbind();$mouseTrap.remove();$mouseTrap=null}
if(zoomDiv){zoomDiv.remove();zoomDiv=null}
this.removeBits()};this.fadedOut=function(){if(zoomDiv){zoomDiv.remove();zoomDiv=null}
this.removeBits()};this.controlLoop=function(){if(lens){var x=(mx-sImg.offset().left-(cw*0.5))>>0;var y=(my-sImg.offset().top-(ch*0.5))>>0;if(x<0){x=0}else if(x>(sImg.outerWidth()-cw)){x=(sImg.outerWidth()-cw)}
if(y<0){y=0}else if(y>(sImg.outerHeight()-ch)){y=(sImg.outerHeight()-ch)}
lens.css({left:x,top:y});lens.css('background-position',(-x)+'px '+(-y)+'px');destU=(((x)/sImg.outerWidth())*zoomImage.width)>>0;destV=(((y)/sImg.outerHeight())*zoomImage.height)>>0;currU+=(destU-currU)/opts.smoothMove;currV+=(destV-currV)/opts.smoothMove;zoomDiv.css('background-position',(-(currU>>0)+'px ')+(-(currV>>0)+'px'))}
controlTimer=setTimeout(function(){ctx.controlLoop()},30)};this.init2=function(img,id){filesLoaded++;if(id===1){zoomImage=img}
if(filesLoaded===2){this.init()}};this.init=function(){$('.cloud-zoom-loading',jWin.parent()).remove();$mouseTrap=jWin.parent().append(format("<div class='mousetrap' style='background-image:url(\".\");z-index:999;position:absolute;width:%0px;height:%1px;left:%2px;top:%3px;\'></div>",sImg.outerWidth(),sImg.outerHeight(),0,0)).find(':last');$mouseTrap.bind('mousemove',this,function(event){mx=event.pageX;my=event.pageY});$mouseTrap.bind('mouseleave',this,function(event){clearTimeout(controlTimer);if(lens){lens.fadeOut(299)}
if($tint){$tint.fadeOut(299)}
if(softFocus){softFocus.fadeOut(299)}
zoomDiv.fadeOut(300,function(){ctx.fadedOut()});return false});$mouseTrap.bind('mouseenter',this,function(event){mx=event.pageX;my=event.pageY;zw=event.data;if(zoomDiv){zoomDiv.stop(true,false);zoomDiv.remove()}
var xPos=opts.adjustX,yPos=opts.adjustY;var siw=sImg.outerWidth();var sih=sImg.outerHeight();var w=opts.zoomWidth;var h=opts.zoomHeight;if(opts.zoomWidth=='auto'){w=siw}
if(opts.zoomHeight=='auto'){h=sih}
var appendTo=jWin.parent();switch(opts.position){case'top':yPos-=h;break;case'right':xPos+=siw;break;case'bottom':yPos+=sih;break;case'left':xPos-=w;break;case'inside':w=siw;h=sih;break;default:appendTo=$('#'+opts.position);if(!appendTo.length){appendTo=jWin;xPos+=siw;yPos+=sih}else{w=appendTo.innerWidth();h=appendTo.innerHeight()}}
zoomDiv=appendTo.append(format('<div id="cloud-zoom-big" class="cloud-zoom-big" style="display:none;position:absolute;left:%0px;top:%1px;width:%2px;height:%3px;background-image:url(\'%4\');z-index:99;"></div>',xPos,yPos,w,h,zoomImage.src)).find(':last');if(sImg.attr('title')&&opts.showTitle){zoomDiv.append(format('<div class="cloud-zoom-title">%0</div>',sImg.attr('title'))).find(':last').css('opacity',opts.titleOpacity)}
if($.browser.msie&&$.browser.version<7){$ie6Fix=$('<iframe frameborder="0" src="#"></iframe>').css({position:"absolute",left:xPos,top:yPos,zIndex:99,width:w,height:h}).insertBefore(zoomDiv)}
zoomDiv.fadeIn(500);if(lens){lens.remove();lens=null}
cw=(sImg.outerWidth()/zoomImage.width)*zoomDiv.width();ch=(sImg.outerHeight()/zoomImage.height)*zoomDiv.height();lens=jWin.append(format("<div class = 'cloud-zoom-lens' style='display:none;z-index:98;position:absolute;width:%0px;height:%1px;'></div>",cw,ch)).find(':last');$mouseTrap.css('cursor',lens.css('cursor'));var noTrans=false;if(opts.tint){lens.css('background','url("'+sImg.attr('src')+'")');$tint=jWin.append(format('<div style="display:none;position:absolute; left:0px; top:0px; width:%0px; height:%1px; background-color:%2;" />',sImg.outerWidth(),sImg.outerHeight(),opts.tint)).find(':last');$tint.css('opacity',opts.tintOpacity);noTrans=true;$tint.fadeIn(500)}
if(opts.softFocus){lens.css('background','url("'+sImg.attr('src')+'")');softFocus=jWin.append(format('<div style="position:absolute;display:none;top:2px; left:2px; width:%0px; height:%1px;" />',sImg.outerWidth()-2,sImg.outerHeight()-2,opts.tint)).find(':last');softFocus.css('background','url("'+sImg.attr('src')+'")');softFocus.css('opacity',0.5);noTrans=true;softFocus.fadeIn(500)}
if(!noTrans){lens.css('opacity',opts.lensOpacity)}
if(opts.position!=='inside'){lens.fadeIn(500)}
zw.controlLoop();return})};img1=new Image();$(img1).load(function(){ctx.init2(this,0)});img1.src=sImg.attr('src');img2=new Image();$(img2).load(function(){ctx.init2(this,1)});img2.src=jWin.attr('href')}
$.fn.CloudZoom=function(options){try{document.execCommand("BackgroundImageCache",false,true)}catch(e){}
this.each(function(){var relOpts,opts;eval('var	a = {'+$(this).attr('rel')+'}');relOpts=a;if($(this).is('.cloud-zoom')){$(this).css({'position':'relative','display':'block'});$('img',$(this)).css({'display':'block'});if($(this).parent().attr('id')!='wrap'){$(this).wrap('<div id="wrap" style="top:0px;z-index:9999;position:relative;"></div>')}
opts=$.extend({},$.fn.CloudZoom.defaults,options);opts=$.extend({},opts,relOpts);$(this).data('zoom',new CloudZoom($(this),opts))}else if($(this).is('.cloud-zoom-gallery')){opts=$.extend({},relOpts,options);$(this).data('relOpts',opts);$(this).bind('click',$(this),function(event){var data=event.data.data('relOpts');$('#'+data.useZoom).data('zoom').destroy();$('#'+data.useZoom).attr('href',event.data.attr('href'));$('#'+data.useZoom+' img').attr('src',event.data.data('relOpts').smallImage);$('#'+event.data.data('relOpts').useZoom).CloudZoom();return false})}});return this};$.fn.CloudZoom.defaults={zoomWidth:'auto',zoomHeight:'auto',position:'right',tint:false,tintOpacity:0.5,lensOpacity:0.5,softFocus:false,smoothMove:3,showTitle:true,titleOpacity:0.5,adjustX:0,adjustY:0}})(jQuery);;(function($){var h=$.scrollTo=function(a,b,c){$(window).scrollTo(a,b,c)};h.defaults={axis:'xy',duration:parseFloat($.fn.jquery)>=1.3?0:1,limit:true};h.window=function(a){return $(window)._scrollable()};$.fn._scrollable=function(){return this.map(function(){var a=this,isWin=!a.nodeName||$.inArray(a.nodeName.toLowerCase(),['iframe','#document','html','body'])!=-1;if(!isWin)return a;var b=(a.contentWindow||a).document||a.ownerDocument||a;return/webkit/i.test(navigator.userAgent)||b.compatMode=='BackCompat'?b.body:b.documentElement})};$.fn.scrollTo=function(e,f,g){if(typeof f=='object'){g=f;f=0}
if(typeof g=='function')g={onAfter:g};if(e=='max')e=9e9;g=$.extend({},h.defaults,g);f=f||g.duration;g.queue=g.queue&&g.axis.length>1;if(g.queue)f/=2;g.offset=both(g.offset);g.over=both(g.over);return this._scrollable().each(function(){if(e==null)return;var d=this,$elem=$(d),targ=e,toff,attr={},win=$elem.is('html,body');switch(typeof targ){case'number':case'string':if(/^([+-]=?)?\d+(\.\d+)?(px|%)?$/.test(targ)){targ=both(targ);break}
targ=$(targ,this);if(!targ.length)return;case'object':if(targ.is||targ.style)toff=(targ=$(targ)).offset()}
$.each(g.axis.split(''),function(i,a){var b=a=='x'?'Left':'Top',pos=b.toLowerCase(),key='scroll'+b,old=d[key],max=h.max(d,a);if(toff){attr[key]=toff[pos]+(win?0:old-$elem.offset()[pos]);if(g.margin){attr[key]-=parseInt(targ.css('margin'+b))||0;attr[key]-=parseInt(targ.css('border'+b+'Width'))||0}
attr[key]+=g.offset[pos]||0;if(g.over[pos])attr[key]+=targ[a=='x'?'width':'height']()*g.over[pos]}else{var c=targ[pos];attr[key]=c.slice&&c.slice(-1)=='%'?parseFloat(c)/100*max:c}if(g.limit&&/^\d+$/.test(attr[key]))attr[key]=attr[key]<=0?0:Math.min(attr[key],max);if(!i&&g.queue){if(old!=attr[key])animate(g.onAfterFirst);delete attr[key]}});animate(g.onAfter);function animate(a){$elem.animate(attr,f,g.easing,a&&function(){a.call(this,e,g)})}}).end()};h.max=function(a,b){var c=b=='x'?'Width':'Height',scroll='scroll'+c;if(!$(a).is('html,body'))return a[scroll]-$(a)[c.toLowerCase()]();var d='client'+c,html=a.ownerDocument.documentElement,body=a.ownerDocument.body;return Math.max(html[scroll],body[scroll])-Math.min(html[d],body[d])};function both(a){return typeof a=='object'?a:{top:a,left:a}}})(jQuery);$(document).ready(function(e){var $cycleHolder=$('.slideshow'),$cycleSlideshow=$('.cycle-slideshow');if($cycleHolder.length>0){$('.slideshow').cycle();}
if($cycleSlideshow.length>0){$('.cycle-slideshow').cycle();}
var $productPageNav=$('#spyMenuTarget ul');if($productPageNav.length>0){var $child=$productPageNav.find('a').each(function(index,element){$(this).click(function(){$.scrollTo($(this).attr('href'),800);})});}});$(document).delegate('a.scrollTop','click',function(e){e.preventDefault();$target=$('body');$.scrollTo($target,400);});$(document).delegate('a.filter','click',function(e){e.preventDefault();$('.product-filter').slideToggle(300);$('.filter').toggleClass('active');});$(document).delegate('#mobileNav','click',function(){var $navheight=$('.nav-collapse').height();$('.nav-collapse').toggleClass('openmenu');});$(document).delegate('#subNav','click',function(){$(this).parent().parent().find('.nav-collapse').toggleClass('openmenu');});$(document).delegate('#country','click',function(){$(this).find('.langlist').show();});$(document).delegate('.langlist','mouseleave',function(){$(this).hide();});if($(window).width()>960){$(document).delegate('.nav > li','mouseover',function(){$(this).addClass('open');});$(document).delegate('.nav > li','mouseout',function(){$(this).removeClass('open');});$(document).undelegate('.nav > li','click',function(){$(this).toggleClass('open');});}else{$(document).undelegate('.nav > li','mouseover',function(){$(this).addClass('open');});$(document).undelegate('.nav > li','mouseout',function(){$(this).removeClass('open');});$(document).delegate('.nav > li','click',function(){$(this).toggleClass('open');});}
window.onload=function(){var $myURL=document.location.href;var $query=$myURL.indexOf('?');if($query!=-1){$getanchor=$myURL.substring($query+1,$myURL.length);var $tgt=$('#'+$getanchor);$('body').delay(500).scrollTo($tgt,300,{offset:-60});}}
$('#gallery .animatorDiv').mouseover(function(){$(this).stop().animate({width:'-=2'},{queue:false,duration:200})})
$('#gallery .animatorDiv').mouseleave(function(){$(this).stop().animate({width:'+=2'},{queue:false,duration:200})})
$('._prodSpec').mouseover(function(){$(this).stop().css({'position':'relative'}).animate({'left':-10},{queue:false,duration:200})})
$('._prodSpec').mouseleave(function(){$(this).stop().animate({'left':0},{queue:false,duration:200})})
$('.prod-block-small').hover(function(){$(this).find('.prod-block-hover').fadeIn(300);},function(){$(this).find('.prod-block-hover').fadeOut(100);});$('.prod-block-normal').hover(function(){$(this).find('.prod-block-hover-large').fadeIn(300);},function(){$(this).find('.prod-block-hover-large').fadeOut(100);});$('#_prodMain .mainProduct').css({'opacity':0.5});function _animMainprod(){}
window.setTimeout(function(){$('#_prodMain .mainProduct').animate({'right':0,'opacity':1},{queue:false,duration:500,complete:_animMainprod()})},1000);$(document).ready(function(e){var $productPageNav=$('#spyMenuTarget ul');if($productPageNav.length>0){var $child=$productPageNav.find('a').each(function(index,element){$(this).click(function(){$.scrollTo($(this).attr('href'),800);})});}
$('.scrollTop').click(function(e){e.preventDefault();$target=$('body');$.scrollTo($target,400);});});$(window).resize(function(e){});function globalmenu(){var $bodySize=$('body').width();var $mobiledevice=$('.btn.btn-navbar').is(':visible');$('.nav > li').hover(function(){$(this).addClass('open');},function(){$(this).removeClass('open');})}
window.onload=function(){var $myURL=document.location.href;var $query=$myURL.indexOf('?');if($query!=-1){$getanchor=$myURL.substring($query+1,$myURL.length);var $tgt=$('#'+$getanchor);$('body').delay(500).scrollTo($tgt,300,{offset:-60});}}
$(document).ready(function(e){var gw=$('#galleryWrapper'),_closegal=$('#galleryWrapper #galbtnclose'),_largImg=$('#gal-img-large');var fullgallery={_isopen:false,init:function(){gw.css({'width':$('body').width(),'height':$(window).height()});},resetgallery:function(){gw.css({'width':'auto','height':'auto'});},show:function(){gw.css({'width':$('body').width(),'height':$(window).height()}).fadeIn();$('.cycle-slide-active').css({'left':($('#galimgLarge').width()-$('.cycle-slide-active').width())/2});_isopen=true;},cancel:function(){gw.fadeOut(200,function(){gw.css({'width':'auto','height':'auto'});})},next:function(){},prev:function(){}}
fullgallery.init();$('.animatorDiv').click(function(){var imgStr=$(this).attr('rel');$('.cycle-slideshow').cycle('goto',parseInt(imgStr));fullgallery.show();});_closegal.click(function(e){fullgallery.cancel();});});window.onresize=function(){$('#galleryWrapper').css({'width':$('body').width(),'height':$(window).height()});}
$(function(){$('.dropdown').hover(function(){clearTimeout($.data(this,'timer'));$(this).find('.dropdown-menu',this).stop(true,true).slideDown(200);$('.darkness').fadeTo('fast',0.6);},function(){$.data(this,'timer',setTimeout($.proxy(function(){$(this).find('.dropdown-menu',this).stop(true,true).slideUp(200);$('.darkness').fadeOut('fast');},this),200));})})
$('#nav >ul>li').hover(function(){clearTimeout($.data(this,'timer'));$('.menu-sub',this).stop(true,true).slideDown(200);},function(){$.data(this,'timer',setTimeout($.proxy(function(){$('.menu-sub',this).stop(true,true).slideUp(200);},this),200));});$(".back-top").hide();$(function(){$(window).scroll(function(){if($(this).scrollTop()>100){$('.back-top').fadeIn();}else{$('.back-top').fadeOut();}});$('.back-top a, a.mini-logo').click(function(){$('body,html').animate({scrollTop:0},800);return false;});});$(".lava-popup-box").hide(200);$(".quick-view-btn").click(function(){$(".lava-popup-box").fadeIn(200);GetdataNew(this.rel);return false;});$(".popup-close").click(function(){$(".lava-popup-box").fadeOut(300);});function GetdataNew(pid){$.ajax({url:"../Product/quick-view.aspx?PID="+pid+"",type:'post',async:false,beforeSend:function(){$(".lava-loader").show();$(".product-list").css('opacity','0.3');},success:function(data){$('#divpopup').html(data);},complete:function(){$(".lava-loader").hide();$(".product-list").css('opacity','1');}});}
$(document).ready(function(){var checkInProgress=false;var desktopFunctions=function(){}
var mobileFunctions=function(){}
var mobileCheck=function(){if($(window).width()<980){mobileFunctions();$(".footer-menu").hide();$('.expand-btn.active').addClass('active').next().show();$(".expand-btn").click(function(){$(this).toggleClass("active").next().slideToggle("fast");return false;});}
else{desktopFunctions();}
checkInProgress=true;}
mobileCheck();$(window).resize(function(){if(checkInProgress===false){checkInProgress=true;setTimeout(mobileCheck,1000);}});});$(document).keyup(function(e){if(e.keyCode==27){$(".lava-popup-box").fadeOut(500);}});
$('.search-text-box').focus(function(){$(this).animate({width:'120px'},500,function(){});});$('.search-text-box').blur(function(){$(this).animate({width:'50px'},500,function(){});});
$('.tabs li:last-child, .search-category li:last-child, .tab-nav li:last-child, .filter-bar > ul > li:last-child').css('border','none');$('.values-desc li:last-child').css('background','none');$('.search-result li:last-child').css('border-bottom','solid 1px #ececec');$('.lava-dealer-list > li:nth-child(4n)').css('margin-right','0px');$('.top-selling > li:last-child').css('padding','0 0 0 30px');